# Setup
title:        Phoenix Peak -  Professional SaaS Consulting
tagline:      Optimize your SaaS.
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Michael Hollauf
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
sass:
  sass_dir: _sass
markdown: kramdown
