# Setup
title:        Phoenix Peak -  Professional SaaS Consulting
tagline:      Optimize your SaaS.
baseurl:      ""
locale:       "en"

# About/contact
author:
  name:       Michael Hollauf
  url:        http://yourhomepage.com 

#Others
sass:
  sass_dir: css
